# readthedocs.yml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt

# Configuration spécifique à Sphinx
sphinx:
  configuration: docs/conf.py

# Setup submodules
submodules:
  include: all

